import { useMemo, useState } from "react"
import { Bento1 } from "../Bento/Bento1"
import { Bento2 } from "../Bento/Bento2"
import { Bento3 } from "../Bento/Bento3"
import { Button } from "../Buttons/Button"
import Drawer, { type DrawerProps } from "../Drawer"

type View = "step1" | "step2" | "step3"

function HowToDrawer(props: DrawerProps) {
	const [view, setView] = useState<View>("step1")

	const content = useMemo(() => {
		switch (view) {
			case "step1":
				return <Step1View setView={setView} />
			case "step2":
				return <Step2View setView={setView} />
			case "step3":
				return <Step3View setView={setView} />
		}
	}, [view])

	return (
		<Drawer activeElementKey={view} onAnimationEnd={() => setView("step1")} {...props}>
			{content}
		</Drawer>
	)
}

function Step1View({ setView }: { setView: (view: View) => void }) {
	return (
		<>
			<Drawer.Header>
				<Drawer.Header.Fullbleed className="flex items-center justify-center">
					<Bento1 />
				</Drawer.Header.Fullbleed>
				<Drawer.Header.Title>Choose your items</Drawer.Header.Title>
				<Drawer.Header.Description>
					Go to the merchant’s store and browse for the items you want to redeem.
					<br />
					<br />
					You can pick items priced above or below your balance — you’ll be able to add or deduct
					the difference during checkout.
				</Drawer.Header.Description>
			</Drawer.Header>

			{/* <Drawer.Content>asd</Drawer.Content> */}
			<Drawer.Footer>
				<Button variant="muted" onClick={() => setView("step2")}>
					Continue
				</Button>
			</Drawer.Footer>
		</>
	)
}

function Step2View({ setView }: { setView: (view: View) => void }) {
	return (
		<>
			<Drawer.Header>
				<Drawer.Header.Fullbleed>
					<Bento2 />
				</Drawer.Header.Fullbleed>
				<Drawer.Header.Title>Pay With Pix</Drawer.Header.Title>
				<Drawer.Header.Description>
					Select your items and proceed to checkout, choosing Pix as the payment method.
				</Drawer.Header.Description>
			</Drawer.Header>

			<Drawer.Footer>
				<Button variant="outline" onClick={() => setView("step1")}>
					Back
				</Button>
				<Button onClick={() => setView("step3")}>Continue</Button>
			</Drawer.Footer>
		</>
	)
}

function Step3View({ setView }: { setView: (view: View) => void }) {
	return (
		<>
			<Drawer.Header>
				<Drawer.Header.Fullbleed>
					<Bento3 />
				</Drawer.Header.Fullbleed>
				<Drawer.Header.Title>Copy the Pix Code</Drawer.Header.Title>
				<Drawer.Header.Description>
					Copy the Pix code generated by the merchant and return here to start the redemption
					process.
				</Drawer.Header.Description>
			</Drawer.Header>
			<Drawer.Footer>
				<Button variant="outline" onClick={() => setView("step2")}>
					Back
				</Button>
				<Drawer.Close asChild>
					<Button>Close</Button>
				</Drawer.Close>
			</Drawer.Footer>
		</>
	)
}

export default HowToDrawer
